### ISSUE TITLE
Publishing simple-websocket on conda

### ISSUE THREAD

**Issue by dinhlongviolin1** [miguelgrinberg/simple-websocket#14]
Hi Miguel Grinberg,

Pardon my terrible English. I am using this library by installing it through pip. I am utilizing conda more and more so do you think it is possible to publish this project on conda as I have seen that some of your other projects are also on conda.

**Comment by dinhlongviolin1** [comment]
Thanks for responding so quickly!

I have seen that your flask-socketio project was published on conda https://anaconda.org/conda-forge/flask-socketio

Is it possible that one of your community member release these projects on conda on behalf of you?

**Comment by miguelgrinberg** [comment]
I don't really know. You should research what is the process to request a package to be added. I only publish my packages to the official package repository.
