### ISSUE TITLE
next_ping time can become invalid for high volume data

### ISSUE THREAD

**Issue by Mitch-Martinez** [miguelgrinberg/simple-websocket#16]
I have recently had an issue where my client connection closes after finishing sending a very high volume of data to a simple-websockets server.

I have identified that the ping packets do not get sent during this period of high volume data, this is expected and I think that this just helped me identify where the issue is. For example, say I have my ping interval set to 5 seconds. Then a client connects and then immediately starts sending data continuously for 30 seconds. You would expect no ping packets sent in that entire 30 seconds. After the client finished sending, the server disconnected it because it did not send the pong back fast enough. Usually the client would have the time set by `ping_interval` to pong back to the server, but because no pings were sent for 30 seconds the `next_ping` time is actually 25-30s behind and it causes the `sel.select(next_ping - now)` call to return `None` almost immediately if the client is not fast enough to respond to the ping. 

The `next_ping` value usually never gets backed up like this but in the above situation, lower latency networks do not have the chance to pong back.

`next_ping` should not be incremented by the `ping_interval` but should instead be assigned to `now + self.ping_interval` to always ensure that the `next_ping` is always expected to be in the future.

**Comment by Mitch-Martinez** [comment]
Hmm, well I may just have completely misunderstood when pings should be sent from the server in the `_thread(self)` method, I assumed with the way it was written that pings would be sent on only two conditions because of this call `sel.select(next_ping - now)`
1. The ping_interval had been reached and
2. There is not data to be read from the socket.

I was planning on doing the PR but my computer with the repo on it is acting up so yes I would appreciate if you could make this change yourself, I apologize for not having a PR ready to review.

**Comment by Mitch-Martinez** [comment]
I put in some print statements every time a ping was sent and saw that they were pretty much getting passed over because there was always something to be read from the socket even if the timeout had been reached and select returned immediately.

When can I expect a new release of simple-websockets? I'm using flask-sock for a server and it would be beneficial to me to be able to get an updated version of simple-websockets to avoid patching the code. This really is an edge case but I would expect it to come up every once in a while.

Thanks for your help and knowledge on all of this.

**Comment by miguelgrinberg** [comment]
@Mitch-Martinez you were right, there was a small logic bug, pings could be delayed until the input buffer was empty. I have now corrected it so that pings are emitted even if the other side is sending constantly.

Can I ask you to install the main branch of this repo and test on your side to confirm everything works correctly now? Thanks.

**Comment by Mitch-Martinez** [comment]
Just finished testing, seems to work as expected. Pings are sent at the expected interval and the next_interval has been corrected. Thank you for taking a closer look at all of this, I appreciate your time on it.

**Comment by miguelgrinberg** [comment]
Okay, yeah, the current solution actually works well when the system is busy sending lots of messages, but using `now` breaks when there is not much activity. I was trying to avoid calling the OS again to get the time, but maybe that's the correct solution anyway.

**Comment by miguelgrinberg** [comment]
@Mitch-Martinez Please retest with current main branch code. Thanks!

**Comment by miguelgrinberg** [comment]
This is now release in v0.7.0. If there are any remaining issues please open a new ticket.
