### ISSUE TITLE
CloseConnection wrong params

### ISSUE THREAD

**Issue by NguyenKhong** [miguelgrinberg/simple-websocket#25]
This a line out_data = self.ws.send(CloseConnection(reason or CloseReason.NORMAL_CLOSURE, message)) in a ws.py file at line 125, throw exception TypeError: __init__() takes 1 positional argument but 3 were given.

The class CloseConnection only accept **kwargs but pass into *args, so it throw a exception. I so hope the author will fix it.

**Comment by miguelgrinberg** [comment]
I don't think you are correct. I tested this in a Python session:

```python
>>> from wsproto.events import CloseConnection
>>> c = CloseConnection(1000, 'close')
>>> c
CloseConnection(code=1000, reason='close')
```

What version of wsproto do you have installed in your virtualenv?
