### ISSUE TITLE
wsproto.utilities.RemoteProtocolError: unrecognized subprotocol settings

### ISSUE THREAD

**Issue by enjaxx** [miguelgrinberg/simple-websocket#36]
Environment:
- simple_websocket: 1.0.0
- wsproto: 1.2.0
- h11: 0.14.0
- linux
- python: 3.10.12

Trying to connect to a custom server, I get the above error. My code:

```       
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
self.ws = simple_websocket.Client.connect(f"wss://{self._ip}/", ssl_context=ctx)
```

self._ip is just a regular local ip, the server is using a self signed certificate, so I have to create a custom ssl context. I'm not using any subprotocols...

**Comment by miguelgrinberg** [comment]
I need to see the complete stack trace of the error, please.

**Comment by enjaxx** [comment]
Sorry for bothering you, I've tested the code with a different library and it throws the same error. It seems to be a problem on the server side.
